#!/bin/bash
# Wrapper script to manage the TemplateVM build process.
# Clones the qubes-builder repo, as well as the securedrop-workstation repo,
# and generates an RPM that can be installed in dom0 to support new TemplateVMs.
set -e
set -u
set -o pipefail

repo_root="$(git rev-parse --show-toplevel)"
build_dir="${repo_root}"
qubes_builder_dir="${build_dir}/qubes-builder"
gpg_homedir="${repo_root}/qubes-builder/keyrings/git"
gpg_homedir_sdw="${gpg_homedir}/template-securedrop-workstation"

# Chroot may exist due to previous failed build; let's clean up responsibly.
if [[ -d "${qubes_builder_dir}" ]]
then
    # Command exits 0 even if no chroot exists.
    make -C "${qubes_builder_dir}" clean-chroot
fi

# Heavy-handed, but ensures build is clean, and also sidesteps idempotence
# issues with the git clone/checkout commands.
rm -rf "${qubes_builder_dir}"

# Make sure to add the corresponding pubkey for the signed tag to the gpg import tasks below.
git clone https://github.com/qubesos/qubes-builder "${build_dir}/qubes-builder"

cd "${qubes_builder_dir}"

# Provision securedrop-workstation config so that we get the correct sources via `make get-sources`.
cp "${repo_root}/securedrop-workstation.conf" builder.conf

# Get sources for only the builder component, which will get Qubes dev keys and initialize the keyring
make COMPONENTS="builder" get-sources
mkdir -m 700 "${gpg_homedir_sdw}"

# Add signing key to the keyring. The pubkey fingerprint tracked here is the SecureDrop
# Release Signing Key. Temporarily, we'll authorize use of two signing keys, for rotation.
# In order to test PRs, you may want to use a personal key with a temporary signed tag.
# See README regarding feature branches for testing changes.
release_key_fingerprint_2020="22245C81E3BAEB4138B36061310F561200F4AD77"
release_key_fingerprint_2021="2359E6538C0613E652955E6C188EDD3B7B22E6A3"
for k in "$release_key_fingerprint_2020" "$release_key_fingerprint_2021"; do
    for d in "$gpg_homedir" "$gpg_homedir_sdw"; do
        gpg --homedir "$d" --keyserver keys.openpgp.org --recv-key "$k"
        echo "${k}:6:" | gpg --homedir "$d" --import-ownertrust
    done
done

# Get all sources
make get-sources

# Install dependencies from Qubes builder logic.
make install-deps

# Build it!
make qubes-vm
make template

# Report location of RPM package
rpm_location="$(sudo find -type f -name 'qubes-template-securedrop-workstation*.rpm')"
echo "Build finished. RPM package available at:"
echo "$rpm_location"
